export enum ErrorCode {
  STRATEGY_NOT_ACTIVE = 'STRATEGY_NOT_ACTIVE',
  STRATEGY_NOT_FOUND = 'STRATEGY_NOT_FOUND',
  STRATEGY_PARAMETERS_INVALID = 'STRATEGY_PARAMETERS_INVALID',
  STRATEGY_PORTFOLIO_NOT_FOUND = 'STRATEGY_PORTFOLIO_NOT_FOUND',
  STRATEGY_EXECUTION_FAILED = 'STRATEGY_EXECUTION_FAILED',
  STRATEGY_EXECUTION_SUCCESS = 'STRATEGY_EXECUTION_SUCCESS',
  STRATEGY_EXECUTION_PARTIAL_SUCCESS = 'STRATEGY_EXECUTION_PARTIAL_SUCCESS',
  STRATEGY_EXECUTION_PARTIAL_FAILED = 'STRATEGY_EXECUTION_PARTIAL_FAILED',
  STRATEGY_EXECUTION_PORTFOLIO_FAILED = 'STRATEGY_EXECUTION_PORTFOLIO_FAILED',

  // 投資組合處理錯誤
  PORTFOLIO_EMPTY_POSITIONS = 'PORTFOLIO_EMPTY_POSITIONS',
  PORTFOLIO_INSUFFICIENT_CASH = 'PORTFOLIO_INSUFFICIENT_CASH',
  PORTFOLIO_DATA_INVALID = 'PORTFOLIO_DATA_INVALID',
  PORTFOLIO_STATE_UPDATE_FAILED = 'PORTFOLIO_STATE_UPDATE_FAILED',

  // 持倉處理錯誤
  POSITION_DATA_INVALID = 'POSITION_DATA_INVALID',
  POSITION_QUANTITY_INVALID = 'POSITION_QUANTITY_INVALID',
  POSITION_PRICE_FETCH_FAILED = 'POSITION_PRICE_FETCH_FAILED',
  POSITION_ADJUSTMENT_FAILED = 'POSITION_ADJUSTMENT_FAILED',
  POSITION_CREATION_FAILED = 'POSITION_CREATION_FAILED',

  // 五線譜策略錯誤
  FIVE_LINE_INSUFFICIENT_DATA = 'FIVE_LINE_INSUFFICIENT_DATA',
  FIVE_LINE_INVALID_PARAMETERS = 'FIVE_LINE_INVALID_PARAMETERS',
  FIVE_LINE_CALCULATION_FAILED = 'FIVE_LINE_CALCULATION_FAILED',
  FIVE_LINE_POSITION_PROCESSING_FAILED = 'FIVE_LINE_POSITION_PROCESSING_FAILED',

  // 指標信號策略錯誤
  INDICATOR_SIGNAL_INVALID_CONDITIONS = 'INDICATOR_SIGNAL_INVALID_CONDITIONS',
  INDICATOR_SIGNAL_EVALUATION_FAILED = 'INDICATOR_SIGNAL_EVALUATION_FAILED',

  // 資產配置策略錯誤
  ASSET_ALLOCATION_INVALID_TARGET = 'ASSET_ALLOCATION_INVALID_TARGET',
  ASSET_ALLOCATION_REBALANCE_FAILED = 'ASSET_ALLOCATION_REBALANCE_FAILED',
  ASSET_ALLOCATION_CALCULATION_FAILED = 'ASSET_ALLOCATION_CALCULATION_FAILED',
  ASSET_ALLOCATION_ANALYSIS_FAILED = 'ASSET_ALLOCATION_ANALYSIS_FAILED',
  ASSET_ALLOCATION_GROUP_PROCESSING_FAILED = 'ASSET_ALLOCATION_GROUP_PROCESSING_FAILED',
  ASSET_ALLOCATION_POSITION_ADJUSTMENT_FAILED = 'ASSET_ALLOCATION_POSITION_ADJUSTMENT_FAILED',
  ASSET_ALLOCATION_NEW_POSITION_FAILED = 'ASSET_ALLOCATION_NEW_POSITION_FAILED',

  // 網格交易策略錯誤
  GRID_TRADING_INVALID_GRID_SETUP = 'GRID_TRADING_INVALID_GRID_SETUP',
  GRID_TRADING_CALCULATION_FAILED = 'GRID_TRADING_CALCULATION_FAILED',
  GRID_TRADING_POSITION_PROCESSING_FAILED = 'GRID_TRADING_POSITION_PROCESSING_FAILED',
  GRID_TRADING_GRID_STATE_FAILED = 'GRID_TRADING_GRID_STATE_FAILED',
  GRID_TRADING_ORDER_GENERATION_FAILED = 'GRID_TRADING_ORDER_GENERATION_FAILED',

  // 數據相關錯誤
  INSUFFICIENT_HISTORICAL_DATA = 'INSUFFICIENT_HISTORICAL_DATA',
  INVALID_MARKET_DATA = 'INVALID_MARKET_DATA',
  MARKET_DATA_FETCH_FAILED = 'MARKET_DATA_FETCH_FAILED',
  PRICE_DATA_INVALID = 'PRICE_DATA_INVALID',
  OHLCV_DATA_INVALID = 'OHLCV_DATA_INVALID',

  // 風險管理錯誤
  RISK_PARAMETERS_INVALID = 'RISK_PARAMETERS_INVALID',
  CASH_BALANCE_INSUFFICIENT = 'CASH_BALANCE_INSUFFICIENT',
  POSITION_SIZE_EXCEEDED = 'POSITION_SIZE_EXCEEDED',
  DRAWDOWN_LIMIT_EXCEEDED = 'DRAWDOWN_LIMIT_EXCEEDED',

  // 交易執行錯誤
  TRADE_QUANTITY_INVALID = 'TRADE_QUANTITY_INVALID',
  TRADE_PRICE_INVALID = 'TRADE_PRICE_INVALID',
  TRADE_RECOMMENDATION_FAILED = 'TRADE_RECOMMENDATION_FAILED',
  BUY_ORDER_FAILED = 'BUY_ORDER_FAILED',
  SELL_ORDER_FAILED = 'SELL_ORDER_FAILED',
}
